
package id.co.ahm.jx.sms.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsPush", targetNamespace = "http://tempuri.org/AHMWSPush/SmsPush")
public class SmsPush
    extends Service
{

    private final static URL SMSPUSH_WSDL_LOCATION;
    private final static WebServiceException SMSPUSH_EXCEPTION;
    private final static QName SMSPUSH_QNAME = new QName("http://tempuri.org/AHMWSPush/SmsPush", "SmsPush");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSPUSH_WSDL_LOCATION = url;
        SMSPUSH_EXCEPTION = e;
    }

    public SmsPush() {
        super(__getWsdlLocation(), SMSPUSH_QNAME);
    }

    public SmsPush(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSPUSH_QNAME, features);
    }

    public SmsPush(URL wsdlLocation) {
        super(wsdlLocation, SMSPUSH_QNAME);
    }

    public SmsPush(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSPUSH_QNAME, features);
    }

    public SmsPush(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsPush(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmsPushSoap
     */
    @WebEndpoint(name = "SmsPushSoap")
    public SmsPushSoap getSmsPushSoap() {
        return super.getPort(new QName("http://tempuri.org/AHMWSPush/SmsPush", "SmsPushSoap"), SmsPushSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsPushSoap
     */
    @WebEndpoint(name = "SmsPushSoap")
    public SmsPushSoap getSmsPushSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/AHMWSPush/SmsPush", "SmsPushSoap"), SmsPushSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SmsPushSoap
     */
    @WebEndpoint(name = "SmsPushSoap12")
    public SmsPushSoap getSmsPushSoap12() {
        return super.getPort(new QName("http://tempuri.org/AHMWSPush/SmsPush", "SmsPushSoap12"), SmsPushSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsPushSoap
     */
    @WebEndpoint(name = "SmsPushSoap12")
    public SmsPushSoap getSmsPushSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/AHMWSPush/SmsPush", "SmsPushSoap12"), SmsPushSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSPUSH_EXCEPTION!= null) {
            throw SMSPUSH_EXCEPTION;
        }
        return SMSPUSH_WSDL_LOCATION;
    }

}
